### ISSUE TITLE
Help needed to add lolcat to path and naming it as lolcat-c in manjaro.

### ISSUE THREAD

**Issue by Scemworks** [dosentmatter/rainbow-zsh-prompt#5]
How to add lolcat to path and name it as lolcat-c in manjaro kde.

**Comment by dosentmatter** [comment]
I read that manjaro's default shell is `bash`. Did you switch to `zsh`?

You can just `echo $PATH` and put the `lolcat-c` binary in one of the listed directories. Read [this post](https://unix.stackexchange.com/a/36874/238373) to figure out the most appropriate directory to place the binary in.

**Comment by Scemworks** [comment]
Manjaro kde comes with zsh as default. Anyway thanks for helping.
